export const LOAD_DEVICES_SUCCESS = "LOAD_DEVICES_SUCCESS";
export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const REMOVE_DEVICE_FROM_CART_SUCCESS = "REMOVE_DEVICE_FROM_CART_SUCCESS";
export const CLEAR_CART = "CLEAR_CART";

export const LOAD_DEVICES_FAIL = "LOAD_DEVICES_FAIL";
export const LOAD_CART_FAIL = "LOAD_CART_FAIL";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const REMOVE_DEVICE_FROM_CART_FAIL = "REMOVE_DEVICE_FROM_CART_FAIL";


